[[build.env]]
  name = "NODE_ENV"
  value = "production"

[[build.env]]
  name = "NPM_CONFIG_LOGLEVEL"
  value = "warn"

[[build.env]]
  name = "PORT"
  value = "80"

[[order.group]]
  [[order.group.dependencies]]
    id = "paketo-buildpacks/node-engine"
    version = "0.3.*"

[[order.group]]
  [[order.group.dependencies]]
    id = "paketo-buildpacks/npm"
    version = "0.4.*"

[[order.group]]
  [[order.group.dependencies]]
    id = "paketo-buildpacks/node-run"
    version = "0.3.*"

