apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    tekton.dev/displayName: Buildpacks
    tekton.dev/pipelines.minVersion: 0.17.0
    tekton.dev/platforms: linux/amd64
    tekton.dev/tags: image-build
  generateName: buildkit-multiarch-run-
  labels:
    app.kubernetes.io/version: '0.2'
  namespace: tekton-builds
spec:
  params:
    - name: IMAGE_NAME
      value: mihailo34/simple-nodejs-server:latest
    - name: SOURCE_URL
      value: https://github.com/MihailoPlavsic34/ana-simple-js-server.git
    - name: SOURCE_REFERENCE
      value: main
    - name: PLATFORMS
      value: linux/amd64,linux/arm64
    - name: CONTEXT
      value: ./node-js-app
    - name: DOCKERFILE
      value: ./node-js-app/Dockerfile
  pipelineRef:
    name: buildkit-build-and-push
  taskRunTemplate:
    podTemplate:
      nodeSelector:
        kubernetes.io/arch: amd64
    serviceAccountName: build-bot
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: source-ws
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 1Gi
          storageClassName: nfs-client
        status: {}